export const INPUT_CHANGE = "INPUT_CHANGE";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_SUCCESS = "GET_SUCCESS";
export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const GET_ROLES_SUCCESS = "GET_ROLES_SUCCESS";
export const GET_ROLES_FAILURE = "GET_ROLES_FAILURE";

export const GET_FACULTIES_SUCCESS = "GET_FACULTIES_SUCCESS";
export const GET_FACULTIES_FAILURE = "GET_FACULTIES_FAILURE";

export const GET_RECENT_BLOGS_SUCCESS = "GET_RECENT_BLOGS_SUCCESS";
export const GET_RECENT_BLOGS_FAILURE = "GET_RECENT_BLOGS_FAILURE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const CLEAR_FORM = "CLEAR_FORM";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";
export const PASSWORD_CHANGE_SUCCESS = "PASSWORD_CHANGE_SUCCESS";
export const PASSWORD_CHANGE_FAILURE = "PASSWORD_CHANGE_FAILURE";
export const PASSWORD_CHANGE_FROM_PROFILE_SUCCESS =
  "PASSWORD_CHANGE_FROM_PROFILE_SUCCESS";
export const PASSWORD_CHANGE_FROM_PROFILE_FAILURE =
  "PASSWORD_CHANGE_FROM_PROFILE_FAILURE";
export const SOCIAL_LOGIN_UPDATE_SUCCESS = "SOCIAL_LOGIN_UPDATE_SUCCESS";
export const SOCIAL_LOGIN_UPDATE_FAILURE = "SOCIAL_LOGIN_UPDATE_FAILURE";
export const COURSE_ENROLMENT_SUCCESS = "COURSE_ENROLMENT_SUCCESS";
export const COURSE_ENROLMENT_FAILURE = "COURSE_ENROLMENT_FAILURE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";

export const COURSE_INPUT_CHANGE = "COURSE_INPUT_CHANGE";
export const CLASS_INPUT_CHANGE = "CLASS_INPUT_CHANGE";
export const GET_ALL_COURSES_SUCCESS = "GET_ALL_COURSES_SUCCESS";
export const GET_ALL_COURSES_FAILURE = "GET_ALL_COURSES_FAILURE";
export const GET_SINGLE_COURSE_SUCCESS = "GET_SINGLE_COURSE_SUCCESS";
export const GET_SINGLE_COURSE_FAILURE = "GET_SINGLE_COURSE_FAILURE";
export const POPULATE_DASHBOARD_SUCCESS = "POPULATE_DASHBOARD_SUCCESS";
export const POPULATE_DASHBOARD_FAILURE = "POPULATE_DASHBOARD_FAILURE";

export const PAYMENT_INPUT_CHANGE = "PAYMENT_INPUT_CHANGE";
export const GET_PAYMENT_PLANS_SUCCESS = "GET_PAYMENT_PLANS_SUCCESS";
export const GET_PAYMENT_PLANS_FAILURE = "GET_PAYMENT_PLANS__FAILURE";
export const PAYMENT_VERIFICATION_SUCCESS = "PAYMENT_VERIFICATION_SUCCESS";
export const PAYMENT_VERIFICATION_FAILURE = "PAYMENT_VERIFICATION_FAILURE";

export const LOAD_QUESTIONS_SUCCESS = "LOAD_QUESTIONS_SUCCESS";
export const LOAD_QUESTIONS_FAILURE = "LOAD_QUESTIONS_FAILURE";
export const PAST_QUESTIONS_INPUT_CHANGE = "PAST_QUESTIONS_INPUT_CHANGE";
export const GET_PAST_QUESTION_SUBJECTS_SUCCESS =
  "GET_PAST_QUESTION_SUBJECTS_SUCCESS";
export const GET_PAST_QUESTION_SUBJECTS_FAILURE =
  "GET_PAST_QUESTION_SUBJECTS_FAILURE";
export const FLAG_QUESTION_SUCCESS = "FLAG_QUESTION_SUCCESS";
export const FLAG_QUESTION_FAILURE = "FLAG_QUESTION_FAILURE";
export const SAVE_USER_ANSWER = "SAVE_USER_ANSWER";
export const UPDATE_QUESTION_TAG = "UPDATE_QUESTION_TAG";
export const POPULATE_SUBMITTED_ANSWER = "POPULATE_SUBMITTED_ANSWER";
export const SUBMIT_RESULT_SUCCESS = "SUBMIT_RESULT_SUCCESS";
export const SUBMIT_RESULT_FAILURE = "SUBMIT_RESULT_FAILURE";

export const GET_SUBJECT_AND_RELATED_LESSONS_SUCCESS =
  "GET_SUBJECT_AND_RELATED_LESSONS_SUCCESS";
export const GET_SUBJECT_AND_RELATED_LESSONS_FAILURE =
  "GET_SUBJECT_AND_RELATED_LESSONS_FAILURE";

export const GET_SUBJECT_LESSONS_SUCCESS = "GET_SUBJECT_LESSONS_SUCCESS";
export const GET_SUBJECT_LESSONS_FAILURE = "GET_SUBJECT_LESSONS_FAILURE";

export const GET_SUBJECT_BASIC_DETAILS_SUCCESS =
  "GET_SUBJECT_BASIC_DETAILS_SUCCESS";
export const GET_SUBJECT_BASIC_DETAILS_FAILURE =
  "GET_SUBJECT_BASIC_DETAILS_FAILURE";

export const GET_SUBJECT_PROGRESSES_SUCCESS = "GET_SUBJECT_PROGRESSES_SUCCESS";
export const GET_SUBJECT_PROGRESSES_FAILURE = "GET_SUBJECT_PROGRESSES_FAILURE";

export const GET_SUBJECT_USERS_SUCCESS = "GET_SUBJECT_USERS_SUCCESS";
export const GET_SUBJECT_USERS_FAILURE = "GET_SUBJECT_USERS_FAILURE";

export const GET_SINGLE_CLASS_SUCCESS = "GET_SINGLE_CLASS_SUCCESS";
export const GET_SINGLE_CLASS_FAILURE = "GET_SINGLE_CLASS_FAILURE";

export const GET_CLASSES_SUCCESS = "GET_CLASSES_SUCCESS";
export const GET_CLASSES_FAILURE = "GET_CLASSES_FAILURE";

export const GET_CHILDREN_SUCCESS = "GET_CHILDREN_SUCCESS";
export const GET_CHILDREN_FAILURE = "GET_CHILDREN_FAILURE";
export const UNLINK_CHILD_ACCOUNT_SUCCESS = "UNLINK_CHILD_ACCOUNT_SUCCESS";
export const UNLINK_CHILD_ACCOUNT_FAILURE = "UNLINK_CHILD_ACCOUNT_FAILURE";
export const UNLINK_CHILDREN_ACCOUNT_SUCCESS =
  "UNLINK_CHILDREN_ACCOUNT_SUCCESS";
export const UNLINK_CHILDREN_ACCOUNT_FAILURE =
  "UNLINK_CHILDREN_ACCOUNT_FAILURE";
export const LINK_CHILD_ACCOUNT_SUCCESS = "LINK_CHILD_ACCOUNT_SUCCESS";
export const LINK_CHILD_ACCOUNT_FAILURE = "LINK_CHILD_ACCOUNT_FAILURE";
export const DELETE_CHILD_ACCOUNT_SUCCESS = "DELETE_CHILD_ACCOUNT_SUCCESS";
export const DELETE_CHILD_ACCOUNT_FAILURE = "DELETE_CHILD_ACCOUNT_FAILURE";
export const DELETE_CHILDREN_ACCOUNT_SUCCESS =
  "DELETE_CHILDREN_ACCOUNT_SUCCESS";
export const DELETE_CHILDREN_ACCOUNT_FAILURE =
  "DELETE_CHILDREN_ACCOUNT_FAILURE";

export const CREATE_COMMENT_TO_ANNOUNCEMENT_SUCCESS =
  "CREATE_COMMENT_TO_ANNOUNCEMENT_SUCCESS";
export const CREATE_COMMENT_TO_ANNOUNCEMENT_FAILURE =
  "CREATE_COMMENT_TO_ANNOUNCEMENT_FAILURE";

export const ADD_ANNOUNCEMENT_SUCCESS = "ADD_ANNOUNCEMENT_SUCCESS";
export const ADD_ANNOUNCEMENT_FAILURE = "ADD_ANNOUNCEMENT_FAILURE";

export const CREATE_COMMENT_TO_CONTENT_SUCCESS =
  "CREATE_COMMENT_TO_CONTENT_SUCCESS";
export const CREATE_COMMENT_TO_CONTENT_FAILURE =
  "CREATE_COMMENT_TO_CONTENT_FAILURE";

export const ASSIGN_CONTENT_TO_STUDENT_FAILURE =
  "ASSIGN_CONTENT_TO_STUDENT_FAILURE";
export const ASSIGN_CONTENT_TO_STUDENT_SUCCESS =
  "ASSIGN_CONTENT_TO_STUDENT_SUCCESS";

export const SEND_CLASS_REQUEST_SUCCESS = "SEND_CLASS_REQUEST_SUCCESS";
export const SEND_CLASS_REQUEST_FAILURE = "SEND_CLASS_REQUEST_FAILURE";

export const SEND_CLASS_INVITE_SUCCESS = "SEND_CLASS_INVITE_SUCCESS";
export const SEND_CLASS_INVITE_FAILURE = "SEND_CLASS_INVITE_FAILURE";

export const CHECK_USER_AND_JOIN_CLASS_SUCCESS =
  "CHECK_USER_AND_JOIN_CLASS_SUCCESS";
export const CHECK_USER_AND_JOIN_CLASS_FAILURE =
  "CHECK_USER_AND_JOIN_CLASS_FAILURE";

export const USER_JOIN_THROUGH_INVITE_SUCCESS =
  "USER_JOIN_THROUGH_INVITE_SUCCESS";
export const USER_JOIN_THROUGH_INVITE_FAILURE =
  "USER_JOIN_THROUGH_INVITE_FAILURE";

export const GET_ALL_SEARCH_RESULTS_SUCCESS = "GET_ALL_SEARCH_RESULTS_SUCCESS";
export const GET_ALL_SEARCH_RESULTS_FAILURE = "GET_ALL_SEARCH_RESULTS_FAILURE";

export const SEARCH_INPUT_CHANGE = "SEARCH_INPUT_CHANGE";

export const GET_PERFORMANCE_SUCCESS = "GET_PERFORMANCE_SUCCESS";
export const GET_PERFORMANCE_FAILURE = "GET_PERFORMANCE_FAILURE";

export const GET_PERFORMANCE_IN_CLASS_SUCCESS =
  "GET_PERFORMANCE_IN_CLASS_SUCCESS";
export const GET_PERFORMANCE_IN_CLASS_FAILURE =
  "GET_PERFORMANCE_IN_CLASS_FAILURE";

export const UPDATE_PROFILE_SUCCES = "UPDATE_PROFILE_SUCCES";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const UPDATE_PROFILE_PIC_SUCCESS = "UPDATE_PROFILE_PIC_SUCCESS";
export const UPDATE_PROFILE__PIC_FAILURE = "UPDATE_PROFILE__PIC_FAILURE";

export const GET_ACTIVE_SUBS_SUCCESS = "GET_ACTIVE_SUBS_SUCCESS";
export const GET_ACTIVE_SUBS_FAILURE = "GET_ACTIVE_SUBS_FAILURE";

export const ADD_RECENT_ACTIVITIES_SUCCESS = "ADD_RECENT_ACTIVITIES_SUCCESS";
export const ADD_RECENT_ACTIVITIES_FAILURE = "ADD_RECENT_ACTIVITIES_FAILURE";

export const GET_ALL_SUBJECT_PROGRESSES_SUCCESS =
  "GET_ALL_SUBJECT_PROGRESSES_SUCCESS";
export const GET_ALL_SUBJECT_PROGRESSES_FAILURE =
  "GET_ALL_SUBJECT_PROGRESSES_FAILURE";

export const ADD_SUBJECT_PROGRESS_SUCCESS = "ADD_SUBJECT_PROGRESS_SUCCESS";
export const ADD_SUBJECT_PROGRESS_FAILURE = "ADD_SUBJECT_PROGRESS_FAILURE";

export const ACCEPT_REJECT_CLASSMEMBER_SUCCESS =
  "ACCEPT_REJECT_CLASSMEMBER_SUCCESS";
export const ACCEPT_REJECT_CLASSMEMBER_FAILURE =
  "ACCEPT_REJECT_CLASSMEMBER_FAILURE";

export const ACCEPT_REJECT_PARENT_REQUEST_SUCCESS =
  "ACCEPT_REJECT_PARENT_REQUEST_SUCCESS";
export const ACCEPT_REJECT_PARENT_REQUEST_FAILURE =
  "ACCEPT_REJECT_PARENT_REQUEST_FAILURE";

export const ACCEPT_REJECT_SCHOOL_ADMIN_REQUEST_SUCCESS =
  "ACCEPT_REJECT_SCHOOL_ADMIN_REQUEST_SUCCESS";
export const ACCEPT_REJECT_SCHOOL_ADMIN_REQUEST_FAILURE =
  "ACCEPT_REJECT_SCHOOL_ADMIN_REQUEST_FAILURE";

export const ACCEPT_REJECT_SCHOOL_TEACHER_REQUEST_SUCCESS =
  "ACCEPT_REJECT_SCHOOL_TEACHER_REQUEST_SUCCESS";
export const ACCEPT_REJECT_SCHOOL_TEACHER_REQUEST_FAILURE =
  "ACCEPT_REJECT_SCHOOL_TEACHER_REQUEST_FAILURE";

export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";
export const ADD_CLASS_FAILURE = "ADD_CLASS_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const GET_SINGLE_LESSON_SUCCESS = "GET_SINGLE_LESSON_SUCCESS";
export const GET_SINGLE_LESSON_FAILURE = "GET_SINGLE_LESSON_FAILURE";
export const GET_SEARCH_RESULTS_DETAILS_SUCCESS =
  "GET_SEARCH_RESULTS_DETAILS_SUCCESS";

export const GET_PARENT_CHILDREN_SUCCESS = "GET_PARENT_CHILDREN_SUCCESS";
export const GET_PARENT_CHILDREN_FAILURE = "GET_PARENT_CHILDREN_FAILURE";

export const GET_CURRENT_CHILD_COURSE_SUCCESS =
  "GET_CURRENT_CHILD_COURSE_SUCCESS";
export const GET_CURRENT_CHILD_COURSE_FAILURE =
  "GET_CURRENT_CHILD_COURSE_FAILURE";

export const GET_CURRENT_CHILD_COURSE_SUBJECTS_SUCCESS =
  "GET_CURRENT_CHILD_COURSE_SUBJECTS_SUCCESS";
export const GET_CURRENT_CHILD_COURSE_SUBJECTS_FAILURE =
  "GET_CURRENT_CHILD_COURSE_SUBJECTS_FAILURE";
export const REGISTER_NEW_CHILD_SUCCESS = "REGISTER_NEW_CHILD_SUCCESS";
export const REGISTER_NEW_CHILD_FAILURE = "REGISTER_NEW_CHILD_FAILURE";

export const SET_PARENT_CHILD = "SET_PARENT_CHILD";
export const FETCH_CHILD_ACTIVITIES_SUCCESS = "FETCH_CHILD_ACTIVITIES_SUCCESS";
export const FETCH_CHILD_ACTIVITIES_FAILURE = "FETCH_CHILD_ACTIVITIES_FAILURE";

export const GET_SCHOOL_TEACHERS_SUCCESS = "GET_SCHOOL_TEACHERS_SUCCESS";
export const GET_SCHOOL_TEACHERS_FAILURE = "GET_SCHOOL_TEACHERS_FAILURE";

export const GET_SCHOOL_PROFILE_SUCCESS = "GET_SCHOOL_PROFILE_SUCCESS";
export const GET_SCHOOL_PROFILE_FAILURE = "GET_SCHOOL_PROFILE_FAILURE";

export const GET_SCHOOL_COURSES_SUCCESS = "GET_SCHOOL_COURSES_SUCCESS";
export const GET_SCHOOL_COURSES_FAILURE = "GET_SCHOOL_COURSES_FAILURE";

export const UPLOAD_SCHOOL_COVER_PHOTO_SUCCESS =
  "UPLOAD_SCHOOL_COVER_PHOTO_SUCCESS";
export const UPLOAD_SCHOOL_COVER_PHOTO_FAILURE =
  "UPLOAD_SCHOOL_COVER_PHOTO_FAILURE";

export const UPLOAD_SCHOOL_PROFILE_SUCCESS = "UPLOAD_SCHOOL_PROFILE_SUCCESS";
export const UPLOAD_SCHOOL_PROFILE_FAILURE = "UPLOAD_SCHOOL_PROFILE_FAILURE";

export const UPDATE_CLASS_NAME_SUCCESS = "UPDATE_CLASS_NAME_SUCCESS";
export const UPDATE_CLASS_NAME_FAILURE = "UPDATE_CLASS_NAME_FAILURE";

export const UPLOAD_SCHOOL_LOGO_SUCCESS = "UPLOAD_SCHOOL_LOGO_SUCCESS";
export const UPLOAD_SCHOOL_LOGO_FAILURE = "UPLOAD_SCHOOL_LOGO_FAILURE";

export const SCHOOL_ADD_EXISTING_TEACHER_SUCCESS =
  "SCHOOL_ADD_EXISTING_TEACHER_SUCCESS";
export const SCHOOL_ADD_EXISTING_TEACHER_FAILURE =
  "SCHOOL_ADD_EXISTING_TEACHER_FAILURE";

export const SCHOOL_SIGNUP_FOR_STUDENT_SUCCESS =
  "SCHOOL_SIGNUP_FOR_STUDENT_SUCCESS";
export const SCHOOL_SIGNUP_FOR_STUDENT_FAILURE =
  "SCHOOL_SIGNUP_FOR_STUDENT_FAILURE";

export const SCHOOL_SIGNUP_FOR_ADMIN_SUCCESS =
  "SCHOOL_SIGNUP_FOR_ADMIN_SUCCESS";
export const SCHOOL_SIGNUP_FOR_ADMIN_FAILURE =
  "SCHOOL_SIGNUP_FOR_ADMIN_FAILURE";

export const GET_CLASS_BASICS_SUCCESS = "GET_CLASS_BASICS_SUCCESS";
export const GET_CLASS_BASICS_FAILURE = "GET_CLASS_BASICS_FAILURE";

export const GET_CLASS_MEMBERS_SUCCESS = "GET_CLASS_MEMBERS_SUCCESS";
export const GET_CLASS_MEMBERS_FAILURE = "GET_CLASS_MEMBERS_FAILURE";

export const GET_CLASS_ASSIGNED_CONTENT_SUCCESS =
  "GET_CLASS_ASSIGNED_CONTENT_SUCCESS";
export const GET_CLASS_ASSIGNED_CONTENT_FAILURE =
  "GET_CLASS_ASSIGNED_CONTENT_FAILURE";

export const GET_CLASS_ASSIGNED_CONTENTS_SUCCESS =
  "GET_CLASS_ASSIGNED_CONTENTS_SUCCESS";
export const GET_CLASS_ASSIGNED_CONTENTS_FAILURE =
  "GET_CLASS_ASSIGNED_CONTENTS_FAILURE";

export const GET_CLASS_ANNOUNCEMENTS_SUCCESS =
  "GET_CLASS_ANNOUNCEMENTS_SUCCESS";
export const GET_CLASS_ANNOUNCEMENTS_FAILURE =
  "GET_CLASS_ANNOUNCEMENTS_FAILURE";

export const GET_CLASS_SUBJECTS_SUCCESS = "GET_CLASS_SUBJECTS_SUCCESS";
export const GET_CLASS_SUBJECTS_FAILURE = "GET_CLASS_SUBJECTS_FAILURE";

export const GET_CLASS_PAST_QUESTIONS_SUCCESS =
  "GET_CLASS_PAST_QUESTIONS_SUCCESS";
export const GET_CLASS_PAST_QUESTIONS_FAILURE =
  "GET_CLASS_PAST_QUESTIONS_FAILURE";

export const SCHOOL_DELETE_STUDENT_ACCOUNT_SUCCESS =
  "SCHOOL_DELETE_STUDENT_ACCOUNT_SUCCESS";
export const SCHOOL_DELETE_STUDENT_ACCOUNT_FAILURE =
  "SCHOOL_DELETE_STUDENT_ACCOUNT_FAILURE";

export const DELETE_ASSIGNED_CONTENT_SUCCESS =
  "DELETE_ASSIGNED_CONTENT_SUCCESS";
export const DELETE_ASSIGNED_CONTENT_FAILURE =
  "DELETE_ASSIGNED_CONTENT_FAILURE";

export const SCHOOL_UNLINK_STUDENT_ACCOUNT_SUCCESS =
  "SCHOOL_UNLINK_STUDENT_ACCOUNT_SUCCESS";
export const SCHOOL_UNLINK_STUDENT_ACCOUNT_FAILURE =
  "SCHOOL_UNLINK_STUDENT_ACCOUNT_FAILURE";

export const SCHOOL_DELETE_TEACHER_ACCOUNT_SUCCESS =
  "SCHOOL_DELETE_TEACHER_ACCOUNT_SUCCESS";
export const SCHOOL_DELETE_TEACHER_ACCOUNT_FAILURE =
  "SCHOOL_DELETE_TEACHER_ACCOUNT_FAILURE";

export const SCHOOL_UNLINK_TEACHER_ACCOUNT_SUCCESS =
  "SCHOOL_UNLINK_TEACHER_ACCOUNT_SUCCESS";
export const SCHOOL_UNLINK_TEACHER_ACCOUNT_FAILURE =
  "SCHOOL_UNLINK_TEACHER_ACCOUNT_FAILURE";

export const SCHOOL_INPUT_CHANGE = "SCHOOL_INPUT_CHANGE";
export const GET_PEOPLE_IN_PAYMENT_CLASS_SUCCESS =
  "GET_PEOPLE_IN_PAYMENT_CLASS_SUCCESS";
export const GET_PEOPLE_IN_PAYMENT_CLASS_FAILURE =
  "GET_PEOPLE_IN_PAYMENT_CLASS_FAILURE";

// user dashboard
export const GET_USER_DASHBOARD_ENROLLED_COURSE_SUCCESS =
  "GET_USER_DASHBOARD_ENROLLED_COURSE_SUCCESS";
export const GET_USER_DASHBOARD_ENROLLED_COURSE_FAILURE =
  "GET_USER_DASHBOARD_ENROLLED_COURSE_FAILURE";
export const GET_USER_DASHBOARD_CLASS_MEMBERSHIP_SUCCESS =
  "GET_USER_DASHBOARD_CLASS_MEMBERSHIP_SUCCESS";
export const GET_USER_DASHBOARD_CLASS_MEMBERSHIP_FAILURE =
  "GET_USER_DASHBOARD_CLASS_MEMBERSHIP_FAILURE";
export const GET_USER_DASHBOARD_RECENT_ACTIVITIES_SUCCESS =
  "GET_USER_DASHBOARD_RECENT_ACTIVITIES_SUCCESS";
export const GET_USER_DASHBOARD_RECENT_ACTIVITIES_FAILURE =
  "GET_USER_DASHBOARD_RECENT_ACTIVITIES_FAILURE";
export const GET_USER_DASHBOARD_RECOMMENDATIONS_SUCCESS =
  "GET_USER_DASHBOARD_RECOMMENDATIONS_SUCCESS";
export const GET_USER_DASHBOARD_RECOMMENDATIONS_FAILURE =
  "GET_USER_DASHBOARD_RECOMMENDATIONS_FAILURE";
export const GET_USER_DASHBOARD_PERFORMANCE_SUMMARY_SUCCESS =
  "GET_USER_DASHBOARD_PERFORMANCE_SUMMARY_SUCCESS";
export const GET_USER_DASHBOARD_PERFORMANCE_SUMMARY_FAILURE =
  "GET_USER_DASHBOARD_PERFORMANCE_SUMMARY_FAILURE";

export const GET_USER_DASHBOARD_UNFINISHED_VIDEOS_SUCCESS =
  "GET_USER_DASHBOARD_UNFINISHED_VIDEOS_SUCCESS";
export const GET_USER_DASHBOARD_UNFINISHED_VIDEOS_FAILURE =
  "GET_USER_DASHBOARD_UNFINISHED_VIDEOS_FAILURE";

export const GET_USER_DASHBOARD_TOPTEN_VIDEOS_SUCCESS =
  "GET_USER_DASHBOARD_TOPTEN_VIDEOS_SUCCESS";
export const GET_USER_DASHBOARD_TOPTEN_VIDEOS_FAILURE =
  "GET_USER_DASHBOARD_TOPTEN_VIDEOS_FAILURE";

export const GET_USER_DASHBOARD_FAVOURITE_VIDEOS_SUCCESS =
  "GET_USER_DASHBOARD_FAVOURITE_VIDEOS_SUCCESS";
export const GET_USER_DASHBOARD_FAVOURITE_VIDEOS_FAILURE =
  "GET_USER_DASHBOARD_FAVOURITE_VIDEOS_FAILURE";

export const GET_AFRILEARN_TOPTEN_VIDEOS_SUCCESS =
  "GET_AFRILEARN_TOPTEN_VIDEOS_SUCCESS";
export const GET_AFRILEARN_TOPTEN_VIDEOS_FAILURE =
  "GET_AFRILEARN_TOPTEN_VIDEOS_FAILURE";

// performance analysis
export const GET_SUBJECT_PROGRESS_PERFORMANCE_SUCCESS =
  "GET_SUBJECT_PROGRESS_PERFORMANCE_SUCCESS";
export const GET_SUBJECT_PROGRESS_PERFORMANCE_FAILURE =
  "GET_SUBJECT_PROGRESS_PERFORMANCE_FAILURE";
export const GET_SUBJECT_QUIZ_PERFORMANCE_SUCCESS =
  "GET_SUBJECT_QUIZ_PERFORMANCE_SUCCESS";
export const GET_SUBJECT_QUIZ_PERFORMANCE_FAILURE =
  "GET_SUBJECT_QUIZ_PERFORMANCE_FAILURE";
export const GET_SUBJECT_PAST_QUESTIONS_PERFORMANCE_SUCCESS =
  "GET_SUBJECT_PAST_QUESTIONS_PERFORMANCE_SUCCESS";
export const GET_SUBJECT_PAST_QUESTIONS_PERFORMANCE_FAILURE =
  "GET_SUBJECT_PAST_QUESTIONS_PERFORMANCE_FAILURE";

export const STORE_UNFINISHED_VIDEO_SUCCESS = "STORE_UNFINISHED_VIDEO_SUCCESS";
export const STORE_UNFINISHED_VIDEO_FAILURE = "STORE_UNFINISHED_VIDEO_FAILURE";

export const CLEAR_UNFINISHED_VIDEO_SUCCESS = "CLEAR_UNFINISHED_VIDEO_SUCCESS";
export const CLEAR_UNFINISHED_VIDEO_FAILURE = "CLEAR_UNFINISHED_VIDEO_FAILURE";

export const STORE_FAVOURITE_VIDEO_SUCCESS = "STORE_FAVOURITE_VIDEO_SUCCESS";
export const STORE_FAVOURITE_VIDEO_FAILURE = "STORE_FAVOURITE_VIDEO_FAILURE";
export const REMOVE_FAVOURITE_VIDEO_SUCCESS = "REMOVE_FAVOURITE_VIDEO_SUCCESS";
export const REMOVE_FAVOURITE_VIDEO_FAILURE = "REMOVE_FAVOURITE_VIDEO_FAILURE";

export const ADD_LIKED_VIDEO_SUCCESS = "ADD_LIKED_VIDEO_SUCCESS";
export const ADD_LIKED_VIDEO_FAILURE = "ADD_LIKED_VIDEO_FAILURE";
export const REMOVE_LIKED_VIDEO_SUCCESS = "REMOVE_LIKED_VIDEO_SUCCESS";
export const REMOVE_LIKED_VIDEO_FAILURE = "REMOVE_LIKED_VIDEO_FAILURE";

//comments
export const GET_LESSON_COMMENTS_SUCCESS = "GET_LESSON_COMMENTS_SUCCESS";
export const GET_LESSON_COMMENTS_FAILURE = "GET_LESSON_COMMENTS_FAILURE";
export const COMMENT_INPUT_CHANGE = "COMMENT_INPUT_CHANGE";
export const ADD_LESSON_COMMENT_SUCCESS = "ADD_LESSON_COMMENT_SUCCESS";
export const ADD_LESSON_COMMENT_FAILURE = "ADD_LESSON_COMMENT_FAILURE";
export const LIKE_LESSON_COMMENT_SUCCESS = "LIKE_LESSON_COMMENT_SUCCESS";
export const LIKE_LESSON_COMMENT_FAILURE = "LIKE_LESSON_COMMENT_FAILURE";
export const UNLIKE_LESSON_COMMENT_SUCCESS = "UNLIKE_LESSON_COMMENT_SUCCESS";
export const UNLIKE_LESSON_COMMENT_FAILURE = "UNLIKE_LESSON_COMMENT_FAILURE";
export const ADD_LESSON_COMMENT_REPLY_SUCCESS =
  "ADD_LESSON_COMMENT_REPLY_SUCCESS";
export const ADD_LESSON_COMMENT_REPLY_FAILURE =
  "ADD_LESSON_COMMENT_REPLY_FAILURE";
export const DELETE_LESSON_COMMENT_SUCCESS = "DELETE_LESSON_COMMENT_SUCCESS";
export const DELETE_LESSON_COMMENT_FAILURE = "DELETE_LESSON_COMMENT_FAILURE";
export const UPDATE_LESSON_COMMENT_SUCCESS = "UPDATE_LESSON_COMMENT_SUCCESS";
export const UPDATE_LESSON_COMMENT_FAILURE = "UPDATE_LESSON_COMMENT_FAILURE";
export const SUBJECT_INPUT_CHANGE = "SUBJECT_INPUT_CHANGE";
export const REPORT_LESSON_SUCCESS = "REPORT_LESSON_SUCCESS";
export const REPORT_LESSON_FAILURE = "REPORT_LESSON_FAILURE";
export const ADD_NEW_ADMIN_TO_CLASS_SUCCESS = "ADD_NEW_ADMIN_TO_CLASS_SUCCESS";
export const ADD_NEW_ADMIN_TO_CLASS_FAILURE = "ADD_NEW_ADMIN_TO_CLASS_FAILURE";

export const ADD_POST_TO_FEED_SUCCESS = "ADD_POST_TO_FEED_SUCCESS";
export const ADD_POST_TO_FEED_FAILURE = "ADD_POST_TO_FEED_FAILURE";

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";

export const COMMENT_TO_POST_SUCCESS = "COMMENT_TO_POST_SUCCESS";
export const COMMENT_TO_POST_FAILURE = "COMMENT_TO_POST_FAILURE";

export const LIKE_A_POST_SUCCESS = "LIKE_A_POST_SUCCESS";
export const LIKE_A_POST_FAILURE = "LIKE_A_POST_FAILURE";

export const UNLIKE_A_POST_SUCCESS = "UNLIKE_A_POST_SUCCESS";
export const UNLIKE_A_POST_FAILURE = "UNLIKE_A_POST_FAILURE";

export const LIKE_A_POST_COMMENT_SUCCESS = "LIKE_A_POST_COMMENT_SUCCESS";
export const LIKE_A_POST_COMMENT_FAILURE = "LIKE_A_POST_COMMENT_FAILURE";

export const UNLIKE_A_POST_COMMENT_SUCCESS = "UNLIKE_A_POST_COMMENT_SUCCESS";
export const UNLIKE_A_POST_COMMENT_FAILURE = "UNLIKE_A_POST_COMMENT_FAILURE";

export const SEARCH_FOR_USERS_IN_FEED_SUCCESS =
  "SEARCH_FOR_USERS_IN_FEED_SUCCESS";
export const SEARCH_FOR_USERS_IN_FEED_FAILURE =
  "SEARCH_FOR_USERS_IN_FEED_FAILURE";

export const GET_USERS_IN_MY_FEED_SUCCESS = "GET_USERS_IN_MY_FEED_SUCCESS";
export const GET_USERS_IN_MY_FEED_FAILURE = "GET_USERS_IN_MY_FEED_FAILURE";

export const GET_COURSES_AND_SUBJECTS_IN_FEED_SUCCESS =
  "GET_COURSES_AND_SUBJECTS_IN_FEED_SUCCESS";
export const GET_COURSES_AND_SUBJECTS_IN_FEED_FAILURE =
  "GET_COURSES_AND_SUBJECTS_IN_FEED_FAILURE";

export const SEARCH_FOR_POSTS_IN_FEED_SUCCESS =
  "SEARCH_FOR_POSTS_IN_FEED_SUCCESS";
export const SEARCH_FOR_POSTS_IN_FEED_FAILURE =
  "SEARCH_FOR_POSTS_IN_FEED_FAILURE";

export const FOLLOW_A_USER_IN_FEED_SUCCESS = "FOLLOW_A_USER_IN_FEED_SUCCESS";
export const FOLLOW_A_USER_IN_FEED_FAILURE = "FOLLOW_A_USER_IN_FEED_FAILURE";

export const GET_MY_POSTS_IN_FEED_SUCCESS = "GET_MY_POSTS_IN_FEED_SUCCESS";
export const GET_MY_POSTS_IN_FEED_FAILURE = "GET_MY_POSTS_IN_FEED_FAILURE";

export const GET_MY_FOLLOWINGS_IN_FEED_SUCCESS =
  "GET_MY_FOLLOWINGS_IN_FEED_SUCCESS";
export const GET_MY_FOLLOWINGS_IN_FEED_FAILURE =
  "GET_MY_FOLLOWINGS_IN_FEED_FAILURE";

export const GET_MY_FOLLOWERS_IN_FEED_SUCCESS =
  "GET_MY_FOLLOWERS_IN_FEED_SUCCESS";
export const GET_MY_FOLLOWERS_IN_FEED_FAILURE =
  "GET_MY_FOLLOWERS_IN_FEED_FAILURE";

export const GET_A_USER_PROFILE_IN_FEED_SUCCESS =
  "GET_A_USER_PROFILE_IN_FEED_SUCCESS";
export const GET_A_USER_PROFILE_IN_FEED_FAILURE =
  "GET_A_USER_PROFILE_IN_FEED_FAILURE";

export const ACTIVATE_MT_ACCOUNT_SUCCESS = "ACTIVATE_MT_ACCOUNT_SUCCESS";
export const ACTIVATE_MT_ACCOUNT_FAILURE = "ACTIVATE_MT_ACCOUNT_FAILURE";

export const FEED_INPUT_CHANGE = "FEED_INPUT_CHANGE";

export const GET_USER_STORIES_SUCCESS = "GET_USER_STORIES_SUCCESS";
export const GET_USER_STORIES_FAILURE = "GET_USER_STORIES_FAILURE";