export const INPUT_CHANGE = 'INPUT_CHANGE';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ROLES_SUCCESS = 'GET_ROLES_SUCCESS';
export const GET_ROLES_FAILURE = 'GET_ROLES_FAILURE';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const CLEAR_FORM = 'CLEAR_FORM';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_FAILURE = 'PASSWORD_CHANGE_FAILURE';
export const SOCIAL_LOGIN_UPDATE_SUCCESS = 'SOCIAL_LOGIN_UPDATE_SUCCESS';
export const SOCIAL_LOGIN_UPDATE_FAILURE = 'SOCIAL_LOGIN_UPDATE_FAILURE';
export const COURSE_ENROLMENT_SUCCESS = 'COURSE_ENROLMENT_SUCCESS';
export const COURSE_ENROLMENT_FAILURE = 'COURSE_ENROLMENT_FAILURE';


export const COURSE_INPUT_CHANGE = 'COURSE_INPUT_CHANGE';
export const GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS';
export const GET_ALL_COURSES_FAILURE = 'GET_ALL_COURSES_FAILURE';
export const GET_SINGLE_COURSE_SUCCESS = 'GET_SINGLE_COURSE_SUCCESS';
export const GET_SINGLE_COURSE_FAILURE = 'GET_SINGLE_COURSE_FAILURE';